### ISSUE TITLE
주제 정하기

### ISSUE THREAD

**Issue by egddbr1213** [egddbr1213/OSS-Project-NLN#2]
주제 정하기

**Comment by KyeongTaek** [comment]
심리학 같은 분야를 입력하면 자동으로 관련된 책을 추천해주고, 해당 책을 구매(서점, 중고서점), 대여(도서관)할 수 있는 장소를 알려주는 프로그램도 좋을 것 같습니다.

**Comment by KyeongTaek** [comment]
이때 알려주는 장소는 해당 도서가 구매, 대여가 가능해야 하고, 현재 위치를 기준으로 일정 반경 이내에 있는 곳입니다.

**Comment by KyeongTaek** [comment]
장소 정렬은 탭을 구매와 대여 두 개로 나누어 구매는 가격과 거리순, 대여는 거리순으로 합니다.

**Comment by egddbr1213** [comment]
과제, 자료 등을 연도, 학기, 주차, 과목 별로 정리를 할 수 있도록 도와주는 프로그램

**Comment by KyeongTaek** [comment]
인터넷 상의 뉴스 기사를 내용을 분석해서 어느 전공 관련 뉴스인지 파악하고, 같은 전공의 뉴스는 한 곳에 모아서 관련된 사람들이 관련된 뉴스를 용이하게 볼 수 있게 하는 프로그램/웹도 좋을 것 같습니다.

**Comment by KyeongTaek** [comment]
이 중에서 하고 싶은 주제가 있습니까?
