### ISSUE TITLE
프로젝트 개발 언어

### ISSUE THREAD

**Issue by egddbr1213** [egddbr1213/OSS-Project-NLN#3]
C / C++ / Python / Java

**Comment by egddbr1213** [comment]
저는 지금 당장 다룰 수 있는 언어는 C 입니다

**Comment by KyeongTaek** [comment]
저도 C가 가장 낫긴 합니다.

**Comment by KyeongTaek** [comment]
일단 기본 언어로 C를 하고, C로 하기에 어려운 기능을 하게 되면 그때 python을 고려해보는 건 어떨까요?

**Comment by KyeongTaek** [comment]
예를 들어서, 웹 관련해서는 C를 사용하기가 어렵다는 이야기를 들은 적이 있는 것 같습니다
