### ISSUE TITLE
주제 별 세부사항에 대해서

### ISSUE THREAD

**Issue by egddbr1213** [egddbr1213/OSS-Project-NLN#4]
1. 재고 관리 : 서점에 프로그램 제공 -> 재고 관리 가능
2. 도서 검색 : 일반 이용자의 도서 검색 -> 도서의 정보를 제공 -> 재고 데이터를 토대로 근방의 재고가 있는 서점이 있는지 검색

이외에도 주제 별로 더 있으면 좋을 것 같은 기능 있을까요

**Comment by egddbr1213** [comment]
서점에서 재고 데이터를 넘겨 받는다면 데이터 저장을 어디에 해야 할까요?? 개인 서버 구축?

**Comment by KyeongTaek** [comment]
데이터 저장은 생각해보니까 엑셀이나 메모장 등 파일에 적는 게 저희한테 좋을 것 같습니다

**Comment by KyeongTaek** [comment]
있으면 더 좋을 것 같은 기능으로는 처음에 생각했던 현재 검색하고 있는 책과 비슷한 분야의 책 추천까지 하면 좋을 거 같긴 합니다.
